# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/notforest/Documents/feather-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/notforest/Documents/feather-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/notforest/Documents/feather-engine/CMakeFiles /home/notforest/Documents/feather-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/notforest/Documents/feather-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named feather

# Build rule for target.
feather: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 feather
.PHONY : feather

# fast build rule for target.
feather/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/build
.PHONY : feather/fast

src/core/context2d.o: src/core/context2d.c.o
.PHONY : src/core/context2d.o

# target to build an object file
src/core/context2d.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/context2d.c.o
.PHONY : src/core/context2d.c.o

src/core/context2d.i: src/core/context2d.c.i
.PHONY : src/core/context2d.i

# target to preprocess a source file
src/core/context2d.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/context2d.c.i
.PHONY : src/core/context2d.c.i

src/core/context2d.s: src/core/context2d.c.s
.PHONY : src/core/context2d.s

# target to generate assembly for a file
src/core/context2d.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/context2d.c.s
.PHONY : src/core/context2d.c.s

src/core/controller.o: src/core/controller.c.o
.PHONY : src/core/controller.o

# target to build an object file
src/core/controller.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/controller.c.o
.PHONY : src/core/controller.c.o

src/core/controller.i: src/core/controller.c.i
.PHONY : src/core/controller.i

# target to preprocess a source file
src/core/controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/controller.c.i
.PHONY : src/core/controller.c.i

src/core/controller.s: src/core/controller.c.s
.PHONY : src/core/controller.s

# target to generate assembly for a file
src/core/controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/controller.c.s
.PHONY : src/core/controller.c.s

src/core/lock.o: src/core/lock.c.o
.PHONY : src/core/lock.o

# target to build an object file
src/core/lock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/lock.c.o
.PHONY : src/core/lock.c.o

src/core/lock.i: src/core/lock.c.i
.PHONY : src/core/lock.i

# target to preprocess a source file
src/core/lock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/lock.c.i
.PHONY : src/core/lock.c.i

src/core/lock.s: src/core/lock.c.s
.PHONY : src/core/lock.s

# target to generate assembly for a file
src/core/lock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/lock.c.s
.PHONY : src/core/lock.c.s

src/core/rect.o: src/core/rect.c.o
.PHONY : src/core/rect.o

# target to build an object file
src/core/rect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/rect.c.o
.PHONY : src/core/rect.c.o

src/core/rect.i: src/core/rect.c.i
.PHONY : src/core/rect.i

# target to preprocess a source file
src/core/rect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/rect.c.i
.PHONY : src/core/rect.c.i

src/core/rect.s: src/core/rect.c.s
.PHONY : src/core/rect.s

# target to generate assembly for a file
src/core/rect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/rect.c.s
.PHONY : src/core/rect.c.s

src/core/res.o: src/core/res.c.o
.PHONY : src/core/res.o

# target to build an object file
src/core/res.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/res.c.o
.PHONY : src/core/res.c.o

src/core/res.i: src/core/res.c.i
.PHONY : src/core/res.i

# target to preprocess a source file
src/core/res.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/res.c.i
.PHONY : src/core/res.c.i

src/core/res.s: src/core/res.c.s
.PHONY : src/core/res.s

# target to generate assembly for a file
src/core/res.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/res.c.s
.PHONY : src/core/res.c.s

src/core/scene.o: src/core/scene.c.o
.PHONY : src/core/scene.o

# target to build an object file
src/core/scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/scene.c.o
.PHONY : src/core/scene.c.o

src/core/scene.i: src/core/scene.c.i
.PHONY : src/core/scene.i

# target to preprocess a source file
src/core/scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/scene.c.i
.PHONY : src/core/scene.c.i

src/core/scene.s: src/core/scene.c.s
.PHONY : src/core/scene.s

# target to generate assembly for a file
src/core/scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/core/scene.c.s
.PHONY : src/core/scene.c.s

src/feather.o: src/feather.c.o
.PHONY : src/feather.o

# target to build an object file
src/feather.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/feather.c.o
.PHONY : src/feather.c.o

src/feather.i: src/feather.c.i
.PHONY : src/feather.i

# target to preprocess a source file
src/feather.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/feather.c.i
.PHONY : src/feather.c.i

src/feather.s: src/feather.c.s
.PHONY : src/feather.s

# target to generate assembly for a file
src/feather.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/feather.c.s
.PHONY : src/feather.c.s

src/misc/err.o: src/misc/err.c.o
.PHONY : src/misc/err.o

# target to build an object file
src/misc/err.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/err.c.o
.PHONY : src/misc/err.c.o

src/misc/err.i: src/misc/err.c.i
.PHONY : src/misc/err.i

# target to preprocess a source file
src/misc/err.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/err.c.i
.PHONY : src/misc/err.c.i

src/misc/err.s: src/misc/err.c.s
.PHONY : src/misc/err.s

# target to generate assembly for a file
src/misc/err.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/err.c.s
.PHONY : src/misc/err.c.s

src/misc/intrinsics.o: src/misc/intrinsics.c.o
.PHONY : src/misc/intrinsics.o

# target to build an object file
src/misc/intrinsics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/intrinsics.c.o
.PHONY : src/misc/intrinsics.c.o

src/misc/intrinsics.i: src/misc/intrinsics.c.i
.PHONY : src/misc/intrinsics.i

# target to preprocess a source file
src/misc/intrinsics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/intrinsics.c.i
.PHONY : src/misc/intrinsics.c.i

src/misc/intrinsics.s: src/misc/intrinsics.c.s
.PHONY : src/misc/intrinsics.s

# target to generate assembly for a file
src/misc/intrinsics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/intrinsics.c.s
.PHONY : src/misc/intrinsics.c.s

src/misc/log.o: src/misc/log.c.o
.PHONY : src/misc/log.o

# target to build an object file
src/misc/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/log.c.o
.PHONY : src/misc/log.c.o

src/misc/log.i: src/misc/log.c.i
.PHONY : src/misc/log.i

# target to preprocess a source file
src/misc/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/log.c.i
.PHONY : src/misc/log.c.i

src/misc/log.s: src/misc/log.c.s
.PHONY : src/misc/log.s

# target to generate assembly for a file
src/misc/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/misc/log.c.s
.PHONY : src/misc/log.c.s

src/runtime.o: src/runtime.c.o
.PHONY : src/runtime.o

# target to build an object file
src/runtime.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/runtime.c.o
.PHONY : src/runtime.c.o

src/runtime.i: src/runtime.c.i
.PHONY : src/runtime.i

# target to preprocess a source file
src/runtime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/runtime.c.i
.PHONY : src/runtime.c.i

src/runtime.s: src/runtime.c.s
.PHONY : src/runtime.s

# target to generate assembly for a file
src/runtime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/feather.dir/build.make CMakeFiles/feather.dir/src/runtime.c.s
.PHONY : src/runtime.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... feather"
	@echo "... src/core/context2d.o"
	@echo "... src/core/context2d.i"
	@echo "... src/core/context2d.s"
	@echo "... src/core/controller.o"
	@echo "... src/core/controller.i"
	@echo "... src/core/controller.s"
	@echo "... src/core/lock.o"
	@echo "... src/core/lock.i"
	@echo "... src/core/lock.s"
	@echo "... src/core/rect.o"
	@echo "... src/core/rect.i"
	@echo "... src/core/rect.s"
	@echo "... src/core/res.o"
	@echo "... src/core/res.i"
	@echo "... src/core/res.s"
	@echo "... src/core/scene.o"
	@echo "... src/core/scene.i"
	@echo "... src/core/scene.s"
	@echo "... src/feather.o"
	@echo "... src/feather.i"
	@echo "... src/feather.s"
	@echo "... src/misc/err.o"
	@echo "... src/misc/err.i"
	@echo "... src/misc/err.s"
	@echo "... src/misc/intrinsics.o"
	@echo "... src/misc/intrinsics.i"
	@echo "... src/misc/intrinsics.s"
	@echo "... src/misc/log.o"
	@echo "... src/misc/log.i"
	@echo "... src/misc/log.s"
	@echo "... src/runtime.o"
	@echo "... src/runtime.i"
	@echo "... src/runtime.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

